CREATE DATABASE IF NOT EXISTS student_db;
USE student_db;

CREATE TABLE IF NOT EXISTS student (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  student_id VARCHAR(11) UNIQUE NOT NULL,
  full_name VARCHAR(150) NOT NULL,
  email VARCHAR(150) NOT NULL,
  course VARCHAR(50)
);
 